### ISSUE TITLE
Kiwi demo: JavaScript doesn't work for me locally

### ISSUE THREAD

**Issue by hamirmahal** [evanw/kiwi#32]
[Kiwi demo: JavaScript](https://github.com/evanw/kiwi/blob/master/examples/js.md#kiwi-demo-javascript) doesn't work for me locally.

<details open>
<summary>Terminal output and screenshot</summary>
<br>

```
hamir@WSL2:~/kiwi-js$ ls
kiwi.js  test.kiwi
hamir@WSL2:~/kiwi-js$ npm install kiwi-schema

added 1 package, and audited 382 packages in 1s

52 packages are looking for funding
  run `npm fund` for details

2 vulnerabilities (1 high, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
hamir@WSL2:~/kiwi-js$ batcat test.kiwi 
───────┬───────────────────────────────────────────────────────────────────────────────────
       │ File: test.kiwi
───────┼───────────────────────────────────────────────────────────────────────────────────
   1   │ message Test {
   2   │   int x = 1;
   3   │ }
───────┴───────────────────────────────────────────────────────────────────────────────────
hamir@WSL2:~/kiwi-js$ batcat kiwi.js 
───────┬───────────────────────────────────────────────────────────────────────────────────
       │ File: kiwi.js
───────┼───────────────────────────────────────────────────────────────────────────────────
   1   │ var kiwi = require('kiwi-schema');
   2   │ var fs = require('fs');
   3   │ 
   4   │ var schema = kiwi.compileSchema(fs.readFileSync('test.kiwi', 'utf8'));
   5   │ var buffer = schema.encodeTest({x: 123});
   6   │ var test = schema.decodeTest(buffer);
   7   │ 
   8   │ // Fields in a Kiwi "message" are optional, and will be undefined if omitted
   9   │ if (test.x !== undefined) {
  10   │   console.log('x is', test.x);
  11   │ }
───────┴───────────────────────────────────────────────────────────────────────────────────
hamir@WSL2:~/kiwi-js$ node kiwi.js 
/home/hamir/node_modules/kiwi-schema/js.js:213
    for (let i = 0; i < schema.definitions.length; i++) {
                                           ^

TypeError: Cannot read properties of undefined (reading 'length')
    at compileSchemaJS (/home/hamir/node_modules/kiwi-schema/js.js:213:44)
    at Object.compileSchema (/home/hamir/node_modules/kiwi-schema/js.js:252:29)
    at Object.<anonymous> (/home/hamir/kiwi-js/kiwi.js:4:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
hamir@WSL2:~/kiwi-js$ 
```
![image](https://user-images.githubusercontent.com/43425812/169361997-f718f6cc-685d-45fc-801e-f512438c8f53.png)
</details>

<details open>
<summary>What I tried</summary>
<br>
I did

```js
function compileSchemaJS(schema) {
    let definitions = {};
    let name = schema.package;
    let js = [];
    if (name !== null) {
        js.push('var ' + name + ' = exports || ' + name + ' || {}, exports;');
    }
    else {
        js.push('var exports = exports || {};');
        name = 'exports';
    }
    js.push(name + '.ByteBuffer = ' + name + '.ByteBuffer || require("kiwi-schema").ByteBuffer;');
    console.log(typeof schema); // new
    console.log(schema); // new
    for (let i = 0; i < schema.definitions.length; i++) {
        let definition = schema.definitions[i];
        definitions[definition.name] = definition;
    }
...
```
and that resulted in
```
hamir@WSL2:~/kiwi-js$ node kiwi.js 
string
message Test {
  int x = 1;
}

/home/hamir/node_modules/kiwi-schema/js.js:215
    for (let i = 0; i < schema.definitions.length; i++) {
                                           ^

TypeError: Cannot read properties of undefined (reading 'length')
    at compileSchemaJS (/home/hamir/node_modules/kiwi-schema/js.js:215:44)
    at Object.compileSchema (/home/hamir/node_modules/kiwi-schema/js.js:254:29)
    at Object.<anonymous> (/home/hamir/kiwi-js/kiwi.js:4:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
hamir@WSL2:~/kiwi-js$ 
```
</details>

**Comment by cjhgit** [comment]
same error, how to resolve it?
